import "./globals.css";
import { Bai_Jamjuree } from 'next/font/google'

export const bai_jamjuree_init = Bai_Jamjuree({
     subsets: ['latin'],
     display: 'swap',
     variable: '--font-bai-jamjuree',
     weight: '200',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bai_jamjuree_init.variable} bai_jamjuree`}>{children}</body>
    </html>
  );
}
